### ISSUE TITLE
Glitches & errors when using MnM Subscription-editing via the wp-admin backend

### ISSUE THREAD

**Issue by limist** [kathyisawesome/wc-mnm-subscription-editing#23]
When editing a particular customer's subscription via the WordPress/WooCommerce wp-admin page (as a site admin etc), and when the subscription product is an MnM variation, we're seeing the following glitches and errors (which are likely related, so listing them all here rather than in separate issues):

1. Initial click of the grey "Edit" button doesn't show a spinner or other visual feedback that it's loading.  Some kind of feedback would be helpful as the loading takes 8-10 seconds, before the modal appears to edit the MnM container contents.  Inspect/Console shows warnings and at least 1 error.
2. Case of same MnM size editing i.e. keeping the same MnM variation:  The larger - and + buttons for each product under the Quantity header, don't appear at all.  It is still possible to change each product's quantity by editing the field directly, or using the much smaller mini/arrow buttons in the field.
3. Upsizing or downsizing, i.e. selecting a larger or smaller MnM variation, reveals **three issues**; the first is: The larger - and + quantity adjustment buttons don't work, clicking either has no effect.  But it's still possible to change quantity for a product by editing or using the much smaller mini-buttons in the field.
4. Saving and upsizing or downsizing — **the 2nd issue**: After choosing the correct quantity of products to satisfy the newly chosen container size (BTW the feedbacks on the quantity needed work well, thanks!), clicking the Update button shows a spinner running at least 90 seconds or indefinitely; usually I had to just reload the page. 
5. After saving upsize/downsize, **the 3rd issue**: We do see the correct new quantities and variation, after reloading.  And the Items Subtotal correctly matches the larger/smaller MnM variation. But the discount/coupon, and the Order Total, are stuck on the old incorrect values.  Also: If we click on the Recalculate button, after a long while, the new correct Order Total is shown, but the coupon/discount is lost (even though the UI shows the same coupon is still attached to the subscription).  Finally, if we click the Apply coupon button, and re-enter the coupon code, we see the spinner but it hangs indefinitely; then reloading the page shows the coupon was still not applied.

These issues in the wp-admin backend seem to parallel many of the same issues seen earlier with the customer UI for the subscription in the My Account view-subscription page, so hopefully the corrected code from the latter can be re-used for wp-admin.  HTH, thanks!

**Comment by helgatheviking** [comment]
Thanks Kai. I have noticed I've messed something up (I think it's when I load the template hooks/actions) locally and now the entire Editing screen is missing.. so I will be looking in to that.

I will note that this plugin isn't used at all on the admin side. That's all in core MNM or I guess also Variable Mix and Match. And it's this plugin that uses those same templates just in a new location. I know that's a little pedantic, but I tried to rewrite core to house the reusable parts as much as possible. 

I _will_ check if the current variation is pre-loaded.... that's what helped this plugin on the front-end. But I am still pretty stuck on how to make variable mix and match more performant as a whole. It needs to query rather a lot of data, pulling multiple products from multiple categories for multiple variations. 

The theme's plus/minus buttons are not meant to work in the admin. I'm never going to be able to figure that out for each theme. However, the latest MNM is going to include plus/minus buttons and I should take a look at always forcing them to load in the admin. I'll always have much better control over my own buttons and I already know they work with the VMNM scripts. :) 

Remind me how the coupon is set up? I think it's a recurring discount right?

I will try to dig into VMNM again later in the week.

**Comment by limist** [comment]
@helgatheviking Thanks for the follow up!  The coupon we use here is a recurring discount (via Smart Coupons plugin) that attaches to a subscription.

Pre-loading the current variation should help the initial-load performance, yes.  Not sure what would help beyond that, I assume that db indices are already there for WooC products etc, and that given the stateless nature of PHP requests, object caching wouldn't be straightforward to use...

**Comment by helgatheviking** [comment]
I need to re-test, but it looks like [reloading](https://github.com/kathyisawesome/wc-mnm-variable/blob/f4679f021afbbc254cb833f6fc25028bceb53471/wc-mnm-variable.php#L770) is already handled by the Variable Mix and Match plugin any time there's an order item where it _can_ preload. 

Though I noticed that in the admin it was not pre-selecting the correct attributes... hopefully that's fixed now [here](https://github.com/kathyisawesome/wc-mnm-variable/blob/trunk/includes/wc-mnm-variable-template-functions.php#L298-L303)

I worked out my bugs and [Mix and Match 2.4-beta.5](https://github.com/kathyisawesome/woocommerce-mix-and-match-products/releases/download/2.4.0-beta.5/woocommerce-mix-and-match-products.zip) should (in theory) have order editing functional again. 

However, of course, that introduced issues with editing variable MNM... but that's not entirely surprising as variable MNM is still in a bit of flux as we get these concepts nailed down. Hopefully those are patched up in [beta6](https://github.com/kathyisawesome/wc-mnm-variable/releases/download/1.0.0-rc.6/wc-mnm-variable-1.0.0-rc.6.zip)

So that leaves 2 things:
1. performance - I think i've mentioned this before, but we're beyond my abilities when it comes to pure performance optimization. Variable products are inherently less performant than simple products, and variable MNM is surely worse. I'm not sure what else there is to try... short of rewriting the entire thing to be front-end only and I cannot take on a project that big right now.

2. Saving is timing out and/or taking forever. Can you get the latest updates and test again. Then I will follow up via email to get back into your staging. 

3. Coupons - So I traced this back to WooCommerce core. Once you apply a coupon, if you add new items to the order, the coupon does not automatically apply to then. And when in the admin (actually in the front end too) the mix and match line items are _removed_ and ones with the new configuration are added. And since Woo doesn't apply coupons after the fact, the discounts get lost. I'll have to mull that one over a bit because it's complicated and again, apparently that's how Woo works (to my surprise)

I'm gonna close this here and split them into separate issues at Variable Mix and Match. 

https://github.com/kathyisawesome/wc-mnm-variable/issues/26
https://github.com/kathyisawesome/wc-mnm-variable/issues/27
https://github.com/kathyisawesome/wc-mnm-variable/issues/28
